name: "CI"
description: "Perform CI actions"
runs:
  using: "composite"
  steps:
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: 17
        distribution: 'adopt'
    - name: "Run tests"
      shell: bash
      run: |
        ./gradlew test
    - name: Build with Gradle
      shell: bash
      run: ./gradlew bootJar
