name: CI / CD

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    name: CI / CD
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2
      - name: "CI"
        uses: ./.github/actions/ci
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: "Upload ECR Image"
        id: upload-ecr-image
        uses: ./.github/actions/cd
      - name: "Apply Terraform"
        uses: ./.github/actions/terraform
        with:
          ecr-image: ${{ steps.upload-ecr-image.outputs.ecr-image }}
